### ISSUE TITLE
reverse proxy nginx with docker compose

### ISSUE THREAD

**Issue by akhila1518** [akhila1518/Devops--Training-1#3]
You will create a solution that will have

A nginx reverse proxy
two backed nginx servers.
the nginx reverse proxy will be the one that will be exposed, when access localhost/pageone request will be for container nginx 1, when access localhost/pagetwo, request will be for nginx container 2
nginx1 and nginx 2 both will have a index.html showing the name of each container, container one, container two.

And when access localhost the nginx reverse proxy will balance the connection between container one and container two, when access using browser or curl it will show the container one page index.html or the container two page index.html

Feel free to use gpt to better understand this, but take in mind, you need understand very well the arquitecture.

Also:

- [ ] create a diagrama of the solution using draw io, you need create manually
- [ ] put the code and coumentation in a diferent folder
- [ ] create a very detailed README.md about the solution on the folder, this will be your writen documentation.

This is a basic but at same time high level project that will prepare you to more advancend things related to kubernetes for example.

**Comment by edipoferreira** [comment]
@akhila1518  I did a test and is not working, tried to validated the nginx.conf but have a error,  belo the testing

```shell
root@5b962dacf39b:/etc/nginx# cat nginx.conf 
http {
    upstream backend {
        server nginx1:80;
        server nginx2:80;
    }

    server {
        listen 80;

        location /pageone {
            proxy_pass http://nginx1;
        }

        location /pagetwo {
            proxy_pass http://nginx2;
        }

        location / {
            proxy_pass http://backend;
        }
    }
}
root@5b962dacf39b:/etc/nginx# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2024/10/22 01:12:21 [emerg] 62#62: no "events" section in configuration
nginx: [emerg] no "events" section in configuration
nginx: configuration file /etc/nginx/nginx.conf test failed
root@5b962dacf39b:/etc/nginx# 
``` 

This is the error on docker compose:

```shell
nginx_reverse_proxy-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_reverse_proxy-1  | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_reverse_proxy-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_reverse_proxy-1  | 2024/10/22 01:07:02 [emerg] 1#1: no "events" section in configuration
nginx_reverse_proxy-1  | nginx: [emerg] no "events" section in configuration
nginx_reverse_proxy-1 exited with code 1


```

**Comment by edipoferreira** [comment]
@akhila1518 after fix, please, test with curl and provide evidences, so I can validate locally as well.

**Comment by akhila1518** [comment]
ubuntu@ip-172-31-89-65:~/nginx-reverse-proxy$ curl -I http://44.203.181.247
HTTP/1.1 200 OK
Server: nginx/1.27.2
Date: Fri, 25 Oct 2024 13:59:26 GMT
Content-Type: text/html
Content-Length: 121
Connection: keep-alive
Last-Modified: Fri, 25 Oct 2024 13:13:20 GMT
ETag: "671b9970-79"
Accept-Ranges: bytes

ubuntu@ip-172-31-89-65:~/nginx-reverse-proxy$ curl http://44.203.181.247
<!DOCTYPE html>
<html>
<head>
    <title>Container Two</title>
</head>
<body>
    <h1>Container Two</h1>
</body>
</html>
ubuntu@ip-172-31-89-65:~/nginx-reverse-proxy$ curl -I http://44.203.181.247:80
HTTP/1.1 200 OK
Server: nginx/1.27.2
Date: Fri, 25 Oct 2024 13:59:49 GMT
Content-Type: text/html
Content-Length: 121
Connection: keep-alive
Last-Modified: Fri, 25 Oct 2024 13:13:20 GMT
ETag: "671b9970-79"
Accept-Ranges: bytes

ubuntu@ip-172-31-89-65:~/nginx-reverse-proxy$ curl -IL http://44.203.181.247
HTTP/1.1 200 OK
Server: nginx/1.27.2
Date: Fri, 25 Oct 2024 13:59:58 GMT
Content-Type: text/html
Content-Length: 121
Connection: keep-alive
Last-Modified: Fri, 25 Oct 2024 13:58:21 GMT
ETag: "671ba3fd-79"
Accept-Ranges: bytes

the code is working fine please check...

**Comment by edipoferreira** [comment]
Hice nuevas pruebas e funcion bien.

![Image](https://github.com/user-attachments/assets/2f4455b1-36ae-4b3a-90b0-55fca0a8058f)
